title: Oladapo Giwa-Daramola
email: dapogd@gmail.com
description: >-
  Software Engineer | Blockchain | AI/ML | Kotlin | Python | Solidity
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oladapo01.github.io" # your GitHub Pages URL
linkedin_username: oladapog
github_username: Oladapo01

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Build settings
markdown: kramdown
permalink: pretty

# Navigation
nav:
  - title: "Home"
    url: /index.html
  - title: "Projects"
    url: /projects.html
  - title: "CV"
    url: /assets/Oladapo_Giwa-Daramola.pdf
